name: Deploy Spotify_UI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy website
        run: |
            cd /root/Spotify_UI

            git fetch origin
            git reset --hard origin/main

            sudo rm -rf /usr/share/nginx/html/*

            sudo cp -r * /usr/share/nginx/html/

            sudo systemctl restart nginx
